FROM ubuntu:bionic

RUN apt-get update
ARG DEBIAN_FRONTEND=noninteractive
RUN apt install -y tzdata
RUN apt install -y keyboard-configuration

RUN apt install -y gnupg2
RUN apt install -y lsb-core 

RUN apt install -y python-minimal
RUN apt install -y python-pip
RUN pip install --upgrade pip
RUN pip install awscli
RUN pip install boto3
RUN pip install kafka-python
RUN pip install psycopg2-binary
RUN pip install numpy

RUN sh -c 'echo "deb http://packages.ros.org/ros/ubuntu $(lsb_release -sc) main" > /etc/apt/sources.list.d/ros-latest.list' 
RUN apt-key adv --keyserver 'hkp://keyserver.ubuntu.com:80' --recv-key C1CF6E31E6BADE8868B172B4F42ED6FBAB17C654 
RUN apt-get update

RUN apt install -y ros-melodic-desktop-full 
RUN echo "source /opt/ros/melodic/setup.bash" >> ~/.bashrc
RUN /bin/bash -c "source ~/.bashrc"
RUN apt install -y python-rosdep python-rosinstall python-rosinstall-generator python-wstool build-essential
RUN apt install -y python-rosdep

RUN rosdep init
RUN rosdep update
RUN pip install  catkin_pkg
RUN apt install -y ros-melodic-rosbridge-suite

ENV ROS_ROOT=/opt/ros/melodic/share/ros
ENV PKG_CONFIG_PATH=/opt/ros/melodic/lib/pkgconfig
ENV ROS_PACKAGE_PATH=/opt/ros/melodic/share
ENV ROS_ETC_DIR=/opt/ros/melodic/etc/ros
ENV CMAKE_PREFIX_PATH=/opt/ros/melodic
ENV PYTHONPATH=/opt/ros/melodic/lib/python2.7/dist-packages
ENV LD_LIBRARY_PATH=/opt/ros/melodic/lib
ENV PATH=/opt/ros/melodic/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

RUN apt install -y vim
COPY src /mozart
COPY bin/*.sh /usr/local/bin/

COPY catkin_ws /catkin_ws
RUN rm -rf /catkin_ws/build /catkin_ws/devel
RUN cd /catkin_ws && catkin_make 

ENV PKG_CONFIG_PATH=/catkin_ws/devel/lib/pkgconfig:$PKG_CONFIG_PATH
ENV ROS_PACKAGE_PATH=/catkin_ws/src:$ROS_PACKAGE_PATH
ENV CMAKE_PREFIX_PATH=/catkin_ws/devel:$CMAKE_PREFIX_PATH
ENV PYTHONPATH=/catkin_ws/devel/lib/python2.7/dist-packages:$PYTHONPATH
ENV LD_LIBRARY_PATH=/catkin_ws/devel/lib:$LD_LIBRARY_PATH
